// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv48uqTXLoMoVj4gwbvTnMAWc3INyqY9k',
    appId: '1:1033184374253:web:33e353a008ec17eee28be4',
    messagingSenderId: '1033184374253',
    projectId: 'financify-accounting',
    authDomain: 'financify-accounting.firebaseapp.com',
    storageBucket: 'financify-accounting.appspot.com',
    measurementId: 'G-L59NZXJNE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjPjjWX6LnY4L76H5du02ojHWiqMv9DqI',
    appId: '1:1033184374253:android:83f105d0619d5600e28be4',
    messagingSenderId: '1033184374253',
    projectId: 'financify-accounting',
    storageBucket: 'financify-accounting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj5Mo-FYaiLRTG4dDf174S5MpU96AeJBI',
    appId: '1:1033184374253:ios:000604823aab814ee28be4',
    messagingSenderId: '1033184374253',
    projectId: 'financify-accounting',
    storageBucket: 'financify-accounting.appspot.com',
    iosClientId: '1033184374253-0760akrvass6ahoeij7trrjhivn8iiks.apps.googleusercontent.com',
    iosBundleId: 'com.example.accoutingSoftware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj5Mo-FYaiLRTG4dDf174S5MpU96AeJBI',
    appId: '1:1033184374253:ios:000604823aab814ee28be4',
    messagingSenderId: '1033184374253',
    projectId: 'financify-accounting',
    storageBucket: 'financify-accounting.appspot.com',
    iosClientId: '1033184374253-0760akrvass6ahoeij7trrjhivn8iiks.apps.googleusercontent.com',
    iosBundleId: 'com.example.accoutingSoftware',
  );
}
